name: Check the source code
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install react react-dom bootstrap eslint-plugin-functional eslint husky lint-staged prettier react-bootstrap
      - name: Prettier
        run: prettier --write ./src
      - name: Lint
        run: eslint ./src
